version: "3.9"
services:
  api:
    build: .
    command: npm run dev
    env_file:
      - .dev.env
    volumes:
    - ./:/home/app
    ports:
    - 4000:4000
  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres

